export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUC_LIST_SUCCESS = 'PRODUC_LIST_SUCCESS'
export const PRODUC_LIST_FAIL = 'PRODUC_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUC_DETAILS_SUCCESS = 'PRODUC_DETAILS_SUCCESS'
export const PRODUC_DETAILS_FAIL = 'PRODUC_LIST_FAIL'